on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: questina/c_infrastructure:boost
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: make check

  build:
    runs-on: ubuntu-latest
    container:
      image: questina/c_infrastructure:boost
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: make build

  tests:
    runs-on: ubuntu-latest
    container:
      image: questina/c_infrastructure:boost
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: make tests