on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: questina/c_infrastructure:firsttry
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: questina/c_infrastructure:firsttry
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main.out
  test:
    runs-on: ubuntu-latest
    container: questina/c_infrastructure:firsttry
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test